/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex('menu_items').del()
  await knex('menu_items').insert([
    {
      id: 1,
      name: 'Vegetarian Mini Spring Rolls ( 10 pcs )',
      description: `They ain't summer rolls!`,
      price: 12.0,
      stock: 40,
      image_url: 'vegetarian-mini-spring-rolls.jpeg',
      category_id: 1,
    },
    {
      id: 2,
      name: 'Vegetarian Mini Samosas ( 10 pcs )',
      description: ``,
      price: 12.0,
      stock: 40,
      image_url: 'vegetarian-mini-samosas.jpeg',
      category_id: 1,
    },
    {
      id: 3,
      name: 'Deep Fried Vegetarian Dumplings ( 10 pcs )',
      description: ``,
      price: 13.0,
      stock: 40,
      image_url: 'deep-fried-dumplings.jpeg',
      category_id: 1,
    },

    {
      id: 4,
      name: 'Thai Fried Rice',
      description: `Thai style stir fried rice with Choice of Meat and Vegetables`,
      price: 18.80,
      stock: 40,
      image_url: 'thai-fried-rice.jpeg',
      category_id: 2,
    },
    {
      id: 5,
      name: 'Fried Rice',
      description: ``,
      price: 18.80,
      stock: 40,
      image_url: 'fried-rice.jpeg',
      category_id: 2,
    },
    {
      id: 6,
      name: 'Nasi Goreng',
      description: `Stir fried choice of meat, rice, mixed vegetables and sambal chilli.`,
      price: 18.80,
      stock: 20,
      image_url: 'nasi-goreng.jpeg',
      category_id: 2,
    },
    {
      id: 7,
      name: 'Nasi Goreng + Fried Egg',
      description: `Stir fried choice of meat with egg, rice, mixed vegetables and sambal chilli.`,
      price: 20.80,
      stock: 20,
      image_url: 'nasi-goreng-fried-egg.jpeg',
      category_id: 2,
    },
    {
      id: 8,
      name: 'Prawns Fried Rice',
      description: ``,
      price: 21.80,
      stock: 25,
      image_url: 'prawns-fried-rice.jpeg',
      category_id: 2,
    },
    {
      id: 9,
      name: 'Duck Fried Rice',
      description: ``,
      price: 21.80,
      stock: 20,
      image_url: 'duck-fried-rice.jpeg',
      category_id: 2,
    },
    {
      id: 10,
      name: 'Crispy Pork Fried Rice',
      description: ``,
      price: 21.80,
      stock: 30,
      image_url: 'crispy-pork-fried-rice.jpeg',
      category_id: 2,
    },
    {
      id: 11,
      name: 'Spicy Fried Rice',
      description: ``,
      price: 18.80,
      stock: 20,
      image_url: 'spicy-fried-rice.jpeg',
      category_id: 2,
    },
    {
      id: 12,
      name: 'Pineapple Fried Rice',
      description: `Stir fried choice of meat, egg, rice, vegetables, pineapple and cashew nuts`,
      price: 19.80,
      stock: 20,
      image_url: 'pineapple-fried-rice.jpeg',
      category_id: 2,
    },
    {
      id: 13,
      name: 'Tom Yum Fried Rice',
      description: ``,
      price: 18.80,
      stock: 20,
      image_url: 'tom-yum-fried-rice.jpeg',
      category_id: 2,
    },

    {
      id: 14,
      name: 'Fried Rice With Cashew Nuts',
      description: ``,
      price: 19.80,
      stock: 20,
      image_url: 'fried-rice-with-cashew-nuts.jpeg',
      category_id: 2,
    },
    {
      id: 15,
      name: 'Vegetarian Fried Rice',
      description: `Stir fried rice, mixed vegetables, soya sauce without egg.`,
      price: 18.80,
      stock: 20,
      image_url: 'vegetarian-fried-rice.jpeg',
      category_id: 2,
    },
    {
      id: 16,
      name: 'Tofu Fried Rice',
      description: `Stir fried tofu with egg, rice, mixed vegetables and soya sauce.`,
      price: 18.80,
      stock: 20,
      image_url: 'tofu-fried-rice.jpeg',
      category_id: 2,
    },
    {
      id: 17,
      name: 'Pad Thai',
      description: ``,
      price: 18.80,
      stock: 40,
      image_url: 'pad-thai.jpeg',
      category_id: 3,
    },
    {
      id: 18,
      name: 'Pad Thai Duck',
      description: ``,
      price: 21.80,
      stock: 40,
      image_url: 'pad-thai-duck.jpeg',
      category_id: 3,
    },
    {
      id: 19,
      name: 'Kuey Teow Goreng Duck',
      description: ``,
      price: 21.80,
      stock: 40,
      image_url: 'kuey-teow-goreng-duck.jpeg',
      category_id: 3,
    },
    {
      id: 20,
      name: 'Chow Mein',
      description: `Yellow noodle and vegetables.`,
      price: 18.80,
      stock: 40,
      image_url: 'chow-mein.jpeg',
      category_id: 3,
    },
    {
      id: 21,
      name: 'Singapore Noodles',
      description: ``,
      price: 18.80,
      stock: 40,
      image_url: 'singapore-noodles.jpeg',
      category_id: 3,
    },
    {
      id: 22,
      name: 'Mee Goreng',
      description: `Yellow noodles, egg, carrot, cabbage and bean sprouts.`,
      price: 18.80,
      stock: 40,
      image_url: 'mee-goreng.jpeg',
      category_id: 3,
    },
    {
      id: 23,
      name: 'Tom Yum Fried Noodles',
      description: `Yellow noodles, tom yum flavour and vegetables.`,
      price: 18.80,
      stock: 40,
      image_url: 'tom-yum-fried-noodles.jpeg',
      category_id: 3,
    },
    {
      id: 24,
      name: 'Satay Noodles',
      description: `Yellow noodles, vegetables, peanuts sauce and your choice of meat`,
      price: 18.80,
      stock: 40,
      image_url: 'satay-noodles.jpeg',
      category_id: 3,
    },
    {
      id: 25,
      name: 'Cashew Nuts Noodles',
      description: `Yellow noodles, chilli paste and vegetables.`,
      price: 19.80,
      stock: 40,
      image_url: 'cashew-nuts-noodles.jpeg',
      category_id: 3,
    },
    {
      id: 26,
      name: 'Drunken Noodles (Pad Kee Mao)',
      description: `Stir fried rice noodles with choice of meat, chilli, garlic and basil leaves.`,
      price: 18.80,
      stock: 40,
      image_url: 'drunken-noodles.jpeg',
      category_id: 3,
    },
    {
      id: 27,
      name: 'Char Kuey Teow',
      description: `Flat rice noodles, egg, carrot, cabbage, bean sprouts with sambal chilli`,
      price: 18.80,
      stock: 40,
      image_url: 'char-kuey-teow.jpeg',
      category_id: 3,
    },
    {
      id: 28,
      name: 'Pad See Ew',
      description: `Flat rice noodles, dark soy sauce, egg, vegetables`,
      price: 18.80,
      stock: 40,
      image_url: 'pad-see-ew.jpeg',
      category_id: 3,
    },
    {
      id: 29,
      name: 'Fried Kuey Teow',
      description: `Flat rice noodles, egg, carrot, cabbage and bean sprouts.`,
      price: 18.80,
      stock: 40,
      image_url: 'fried-kuey-teow.jpeg',
      category_id: 3,
    },
    {
      id: 30,
      name: 'Kuey Teow Goreng',
      description: ``,
      price: 18.80,
      stock: 40,
      image_url: 'kuey-teow-goreng.jpeg',
      category_id: 3,
    },
    {
      id: 31,
      name: 'Coke',
      description: `Non-Alcoholic`,
      price: 4.00,
      stock: 40,
      image_url: '',
      category_id: 4,
    },
    {
      id: 32,
      name: 'Diet Coke',
      description: `Non-Alcoholic`,
      price: 4.00,
      stock: 40,
      image_url: '',
      category_id: 4,
    },
    {
      id: 33,
      name: 'Coke Zero',
      description: `Non-Alcoholic`,
      price: 4.00,
      stock: 40,
      image_url: '',
      category_id: 4,
    },
    {
      id: 34,
      name: 'Sprite',
      description: `Non-Alcoholic`,
      price: 4.00,
      stock: 40,
      image_url: '',
      category_id: 4,
    },
    {
      id: 35,
      name: 'Fanta Orange',
      description: `Non-Alcoholic`,
      price: 4.00,
      stock: 40,
      image_url: '',
      category_id: 4,
    },
    {
      id: 36,
      name: 'Raspbery Coke',
      description:'Non-Alcoholic',
      price: 4.50,
      stock: 40,
      image_url: '',
      category_id: 4,
    },
    {
      id: 37,
      name: 'Raspbery Lemonade',
      description:'Non-Alcoholic',
      price: 4.50,
      stock: 40,
      image_url: '',
      category_id: 4,
    },
    {
      id: 38,
      name: 'Ginger Beer',
      description:'Non-Alcoholic',
      price: 5.50,
      stock: 40,
      image_url: '',
      category_id: 4,
    },
    {
      id: 39,
      name: 'Lemon Lime Bitters',
      description:'Non-Alcoholic',
      price: 5.50,
      stock: 40,
      image_url: '',
      category_id: 4,
    },
    {
      id: 40,
      name: 'Thai Mike Tea',
      description:'Non-Alcoholic',
      price: 6.00,
      stock: 40,
      image_url: '',
      category_id: 4,
    },
    {
      id: 41,
      name: 'Coconut Water',
      description:'Non-Alcoholic',
      price: 6.00,
      stock: 40,
      image_url: '',
      category_id: 4,
    },
    {
      id: 42,
      name: 'Mocktail',
      description:'Non-Alcoholic',
      price: 8.00,
      stock: 40,
      image_url: '',
      category_id: 4,
    },
    {
      id: 43,
      name: 'Orange Juice',
      description:'Juice',
      price: 5.00,
      stock: 40,
      image_url: '',
      category_id: 4,
    },
    {
      id: 44,
      name: 'Apple Juice',
      description:'Juice',
      price: 5.00,
      stock: 40,
      image_url: '',
      category_id: 4,
    },
    {
      id: 45,
      name: 'Pineapple Juice',
      description:'Juice',
      price: 5.00,
      stock: 40,
      image_url: '',
      category_id: 4,
    },
    {
      id: 46,
      name: 'Peach Soju',
      description:'Soju',
      price: 14.00,
      stock: 40,
      image_url: '',
      category_id: 4,
    },
    {
      id: 47,
      name: 'GreenGrape Soju',
      description:'Soju',
      price: 14.00,
      stock: 40,
      image_url: '',
      category_id: 4,
    },
    {
      id: 48,
      name: 'Strawberry Soju',
      description:'Soju',
      price: 14.00,
      stock: 40,
      image_url: '',
      category_id: 4,
    },
    {
      id: 49,
      name: 'Watermelon Soju',
      description:'Soju',
      price: 14.00,
      stock: 40,
      image_url: '',
      category_id: 4,
    },
    {
      id: 50,
      name: 'Pineapple Soju',
      description:'Soju',
      price: 14.00,
      stock: 40,
      image_url: '',
      category_id: 4,
    },
    {
      id: 51,
      name: 'Singha',
      description:'Beer',
      price: 9.00,
      stock: 40,
      image_url: '',
      category_id: 4,
    },
    {
      id: 52,
      name: 'Chang',
      description:'Beer',
      price: 9.00,
      stock: 40,
      image_url: '',
      category_id: 4,
    },
    {
      id: 53,
      name: 'Heineken Light',
      description:'Beer',
      price: 9.00,
      stock: 40,
      image_url: '',
      category_id: 4,
    },
    {
      id: 54,
      name: 'Heineken',
      description:'Beer',
      price: 9.00,
      stock: 40,
      image_url: '',
      category_id: 4,
    },
    {
      id: 55,
      name: 'Tiger',
      description:'Beer',
      price: 9.00,
      stock: 40,
      image_url: '',
      category_id: 4,
    },
    {
      id: 56,
      name: 'Asahi',
      description:'Beer',
      price: 9.00,
      stock: 40,
      image_url: '',
      category_id: 4,
    },
    {
      id: 57,
      name: 'Corona',
      description:'Beer',
      price: 9.00,
      stock: 40,
      image_url: '',
      category_id: 4,
    },
    {
      id: 58,
      name: 'Merlot Cabernet',
      description:'Red Wines',
      price: 9.00,
      stock: 40,
      image_url: '',
      category_id: 4,
    },
    {
      id: 59,
      name: 'Shiraz',
      description:'Red Wines',
      price: 9.00,
      stock: 40,
      image_url: '',
      category_id: 4,
    },
    {
      id: 60,
      name: 'Piont Noir',
      description:'Red Wines',
      price: 9.00,
      stock: 40,
      image_url: '',
      category_id: 4,
    },
    {
      id: 61,
      name: 'Sauvignon Blanc',
      description:'White Wines',
      price: 9.00,
      stock: 40,
      image_url: '',
      category_id: 4,
    },

    {
      id: 62,
      name: 'Chardonnay',
      description:'White Wines',
      price: 9.00,
      stock: 40,
      image_url: '',
      category_id: 4,
    },
    {
      id: 63,
      name: 'Pinor Gris',
      description:'White Wines',
      price: 9.00,
      stock: 40,
      image_url: '',
      category_id: 4,
    },
    
    // {
    //   id: 1,
    //   name: 'Spring Rolls',
    //   description: `They ain't summer rolls!`,
    //   price: 30.0,
    //   stock: 40,
    //   image_url: '',
    //   category_id: 1,
    // },
    // {
    //   id: 2,
    //   name: 'Side Salad',
    //   description: `For your sidekick!`,
    //   price: 30.0,
    //   stock: 30,
    //   image_url: '',
    //   category_id: 1,
    // },
    // {
    //   id: 3,
    //   name: 'Chicken Wings',
    //   description: `Good thing chickens already couldn't fly`,
    //   price: 30.0,
    //   stock: 40,
    //   image_url: '',
    //   category_id: 1,
    // },
    // {
    //   id: 4,
    //   name: 'Roast Beast',
    //   description: `Some kind of Dr Seuss reference`,
    //   price: 30.0,
    //   stock: 40,
    //   image_url: '',
    //   category_id: 2,
    // },
    // {
    //   id: 5,
    //   name: 'Pasta Ala Mood',
    //   description: `Americas favourite pasta time`,
    //   price: 30.0,
    //   stock: 40,
    //   image_url: '',
    //   category_id: 2,
    // },
    // {
    //   id: 6,
    //   name: 'Skittle Bräu',
    //   description: `The beer with skittles in it`,
    //   price: 30.0,
    //   stock: 40,
    //   image_url: '',
    //   category_id: 4,
    // },
    // {
    //   id: 7,
    //   name: 'Dessert Island',
    //   description: `We'll give you fun with one bullet`,
    //   price: 30.0,
    //   stock: 40,
    //   image_url: '',
    //   category_id: 3,
    // },
    // {
    //   id: 8,
    //   name: 'A plum floating in perfume, served in a mans hat',
    //   price: 30.0,
    //   description: `Number 8, Number 8, Number 8`,
    //   stock: 40,
    //   image_url: '',
    //   category_id: 4,
    // },
  ])
}
